const MESSAGE_TRANSFER_REMINDER_SET_TYPE = "transferReminderSet";
const MESSAGE_TRANSFER_REMINDER_REMOVE_TYPE = "transferReminderRemove";

export {
    MESSAGE_TRANSFER_REMINDER_SET_TYPE,
    MESSAGE_TRANSFER_REMINDER_REMOVE_TYPE,
};
