const OPTIONS_TAB_HASH_SKILLS_IMPORTANCE = "#skills-importance";
const OPTIONS_TAB_HASH_REMINDERS = "#reminders";
const OPTIONS_TAB_HASH_TRANSFER_FILTERS = "#transfer-filters";

export {
    OPTIONS_TAB_HASH_SKILLS_IMPORTANCE,
    OPTIONS_TAB_HASH_REMINDERS,
    OPTIONS_TAB_HASH_TRANSFER_FILTERS,
};
